on:
  - push
  - pull_request

jobs:
  ubuntu-20_04:
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
      matrix:
        version: [7, 8, 9, 10, 11]

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.version }}

      - run: |
          g++ --version

  ubuntu-22_04:
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: true
      matrix:
        version: [9, 10, 11, 12]

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.version }}

      - run: |
          g++ --version
